version: '3'

services:
  postegres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "filipe"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "filipewk@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "353535"
    ports:
      - "16543:80"
    depends_on:
      - postegres